services:
  ping-bot:
    build: .
    container_name: my_ping_bot
    restart: always
    volumes:
      - ./users_data.json:/app/users_data.json
      - ./account2_session.session:/app/account2_session.session
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
