services:
  ping-bot-prod:
    build: .
    container_name: my_ping_bot_prod
    restart: always
    environment:
      - BOT_MODE=prod # Продакшн режим
    env_file:
      - .env
    volumes:
      - ./users_data.json:/app/users_data.json
      - ./backups:/app/backups
      - ./account2_session_prod.session:/app/account2_session_prod.session
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
