services:
  ping-bot-prod:
    build: .
    container_name: my_ping_bot_prod
    restart: always
    environment:
      - BOT_MODE=prod # Продакшн режим
    env_file:
      - .env
    volumes:
      - ./users_data.json:/app/users_data.json
      - ./backups:/app/backups
      - ./sessions:/app/sessions # All session files persist here
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
