services:
  ping-bot-test:
    build: .
    container_name: ping_test
    restart: always
    environment:
      - BOT_MODE=test # Тестовий режим
    env_file:
      - .env
    volumes:
      - ./data_test:/app/data
      - ./sessions_test:/app/sessions
      - ./.env:/app/.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
